[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
blueshift_anchor_vault = "5H9MDF9yfmGsnFMHaYg7QK6iqsc56aU9kW9XsU8NACRx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
